language: python

sudo: false

env:
    - PYTHON="2.7"
    - PYTHON="3.4"
    - PYTHON="3.5"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --add channels ioos -f
    - conda update --yes --all
    - travis_retry conda create --yes -n test python=$PYTHON nomkl --file requirements.txt
    - source activate test
    - conda install --yes --file requirements-dev.txt;
    - pip install git+https://github.com/python-visualization/branca.git@befdf0bb29ecea488c79147fa1a851e15bfe5a10
    - if [[ "$PYTHON" == "3.4" ]]; then
        travis_retry conda install --yes nbconvert jupyter_client ipykernel;
        conda install --yes -c ioos geopandas;
      fi
    - if [[ "$PYTHON" != "3.5" ]]; then
        travis_retry conda install --yes mock ;
      fi
    - travis_retry pip install

script:
    - python setup.py test
    - find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100
